---
- name: kubeCodeDeploy
  hosts: kube
  become: yes
  tasks:
    - name: Run a command on the target server
      user:
         name: prabhu
         password: "{{ '@Prabhumani' | password_hash('sha512') }}"
