---
- name: kubeCodeDeploy
  hosts: kubeserver
  gather_facts: no 
  tasks:
    - name: Disable SSH strict host key checking
      ansible.cfg:
        lines:
          - "host_key_checking = False"
  
    - name: Run a command on the target server
      shell: echo "df -h"

