---
- name: kubeCodeDeploy
  hosts: kube
  become: true
  tasks:
    - name: Create the namespace
      command: /mydeployment/kubectl create -f mynamespace.yaml

    - name: Create the svc
      command: /mydeployment/kubectl create -f mysvc.yaml -n mypod

    - name: Create the mydeployment
      command: /mydeployment/kubectl create -f mydeployment.yaml -n mypod

