---
- name: Change Directory and Run Multiple Commands
  hosts: kube
  become: true
  tasks:
    - name: Ensure the directory exists
      file:
        path: /home/ec2-user/mydeployment
        state: directory

    - name: Change to the specified directory and run commands
      shell: |
        cd /home/ec2-user/mydeployment
        echo "Hello"
      args:
        executable: /bin/bash

