---
- name: Change Directory and Run Multiple Commands
  hosts: kube
  become: true
  tasks:
    - name: Change to the specified directory and run commands
      shell: 
          kubectl create -f mynamespace.yaml
      args:
        executable: /bin/bash

