---
- name: kubeCodeDeploy
  hosts: kube
  become: true
  tasks:
    - name: Create the namespace
      shell: |
           cd /home/ec2-user/mydeployment
           /kubectl create -f mynamespace.yaml
           /kubectl create -f mysvc.yaml -n mypod
           /kubectl create -f mydeployment.yaml -n mypod
