---
- name: kubeCodeDeploy
  hosts: kubeserver
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Run a command on the target server
      command: df -h
      vars:
        ansible_ssh_private_key_file: /root/.ssh/id_rsa
